spring:

  application:
    name: stocky-api-spring

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

# JWT 설정 (커스텀 설정)
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}      # 1시간 (밀리초)
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}  # 14일 (밀리초)

# AWS 설정
cloud:
  aws:
    credentials:
      # .env 파일에 적힌 값을 가져옵니다
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

# 커스텀 앱 설정
app:
  cors:
    allowed-origins:
      - "http://localhost:3000"
  cookie:
    secure: false       # 로컬은 http니까 false
    same-site: "Lax"    # 로컬은 같은 도메인(localhost)끼리라 Lax면 충분
    refresh-token-expiration: 1209600000 # 14일
  sqs:
    queue:
      # 큐 이름도 환경변수로 빼도 좋지만, 개발/운영 분리가 되어 있다면 하드코딩도 괜찮습니다.
      regular-request: "stocky-regular-request-queue"
      regular-response: "stocky-regular-response-queue"
      urgent-alert: "stocky-urgent-alert-queue"